/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author Chynna
 */
public class AddClassFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddClassFrame
     */
    public AddClassFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClassNameLabel = new javax.swing.JLabel();
        ClassNameField = new javax.swing.JTextField();
        SemesterLabel = new javax.swing.JLabel();
        SemesterField = new javax.swing.JTextField();
        HomeworkLabel = new javax.swing.JLabel();
        HomeworkField = new javax.swing.JTextField();
        LabLabel = new javax.swing.JLabel();
        ExamLabel = new javax.swing.JLabel();
        LabTextField = new javax.swing.JTextField();
        ExamField = new javax.swing.JTextField();
        MidtermLabel = new javax.swing.JLabel();
        FinalExamLabel = new javax.swing.JLabel();
        ProjectLabel = new javax.swing.JLabel();
        AttendanceLabel = new javax.swing.JLabel();
        NumStudentsLabel = new javax.swing.JLabel();
        MidtermTextField = new javax.swing.JTextField();
        FinalExamField = new javax.swing.JTextField();
        ProjectTextField = new javax.swing.JTextField();
        AttendanceField = new javax.swing.JTextField();
        NumStudentsField = new javax.swing.JTextField();
        AddClassDone = new javax.swing.JButton();
        SemesterSelection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Class");

        ClassNameLabel.setText("Class Name:");

        ClassNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassNameFieldActionPerformed(evt);
            }
        });

        SemesterLabel.setText("Semester:");

        SemesterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterFieldActionPerformed(evt);
            }
        });

        HomeworkLabel.setText("Homework Weight:");

        HomeworkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeworkFieldActionPerformed(evt);
            }
        });

        LabLabel.setText("Lab Weight:");

        ExamLabel.setText("Exam Weight:");

        LabTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTextFieldActionPerformed(evt);
            }
        });

        ExamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamFieldActionPerformed(evt);
            }
        });

        MidtermLabel.setText("Midterm Weight:");

        FinalExamLabel.setText("Final Exam Weight:");

        ProjectLabel.setText("Project Weight:");

        AttendanceLabel.setText("Attendance/Participation:");

        NumStudentsLabel.setText("Number of Students");

        MidtermTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MidtermTextFieldActionPerformed(evt);
            }
        });

        FinalExamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalExamFieldActionPerformed(evt);
            }
        });

        ProjectTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectTextFieldActionPerformed(evt);
            }
        });

        AttendanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceFieldActionPerformed(evt);
            }
        });

        NumStudentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumStudentsFieldActionPerformed(evt);
            }
        });

        AddClassDone.setText("Save");
        AddClassDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClassDoneActionPerformed(evt);
            }
        });

        SemesterSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall", "Spring", "Summer" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExamField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HomeworkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HomeworkField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddClassDone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(NumStudentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProjectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(NumStudentsField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(AttendanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(AttendanceField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClassNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SemesterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClassNameField)
                                .addGap(167, 167, 167))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SemesterSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FinalExamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addComponent(MidtermLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FinalExamField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(MidtermTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClassNameField)
                        .addComponent(ClassNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MidtermTextField)
                        .addComponent(MidtermLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SemesterField)
                        .addComponent(SemesterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SemesterSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FinalExamField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(FinalExamLabel)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(ProjectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HomeworkField)
                        .addComponent(HomeworkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AttendanceField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(AttendanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabTextField)
                        .addComponent(LabLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExamField)
                        .addComponent(ExamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NumStudentsField, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(NumStudentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddClassDone)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SemesterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterFieldActionPerformed

    private void HomeworkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeworkFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeworkFieldActionPerformed

    private void LabTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTextFieldActionPerformed

    private void ExamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExamFieldActionPerformed

    private void ClassNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassNameFieldActionPerformed

    private void MidtermTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MidtermTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MidtermTextFieldActionPerformed

    private void FinalExamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalExamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalExamFieldActionPerformed

    private void ProjectTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectTextFieldActionPerformed

    private void AttendanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AttendanceFieldActionPerformed

    private void NumStudentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumStudentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumStudentsFieldActionPerformed

    private void AddClassDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClassDoneActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_AddClassDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClassDone;
    private javax.swing.JTextField AttendanceField;
    private javax.swing.JLabel AttendanceLabel;
    private javax.swing.JTextField ClassNameField;
    private javax.swing.JLabel ClassNameLabel;
    private javax.swing.JTextField ExamField;
    private javax.swing.JLabel ExamLabel;
    private javax.swing.JTextField FinalExamField;
    private javax.swing.JLabel FinalExamLabel;
    private javax.swing.JTextField HomeworkField;
    private javax.swing.JLabel HomeworkLabel;
    private javax.swing.JLabel LabLabel;
    private javax.swing.JTextField LabTextField;
    private javax.swing.JLabel MidtermLabel;
    private javax.swing.JTextField MidtermTextField;
    private javax.swing.JTextField NumStudentsField;
    private javax.swing.JLabel NumStudentsLabel;
    private javax.swing.JLabel ProjectLabel;
    private javax.swing.JTextField ProjectTextField;
    private javax.swing.JTextField SemesterField;
    private javax.swing.JLabel SemesterLabel;
    private javax.swing.JComboBox<String> SemesterSelection;
    // End of variables declaration//GEN-END:variables
}
